### ISSUE TITLE
Use different temp files

### ISSUE THREAD

**Issue by simonzack** [nikku/karma-browserify#100]
I'm in a situation where I have to run 2 karma instances, one for debugging and another for coverage. Due to the sharing of cwd karma-browserify is writing both to the same bundle file. Can the path be specified in the options or be different on each run?

**Comment by bendrucker** [comment]
Yeah there's no reason why there couldn't be some random bits in there. We'll take a PR.

**Comment by bendrucker** [comment]
On its way up as 3.0.2
