### ISSUE TITLE
Some more problems with temp files

### ISSUE THREAD

**Issue by simonzack** [nikku/karma-browserify#102]
Thanks again for the temp file fix. But I've encountered another problem. Turns out it's possible to run two karma instances on the same node process, but karma-browserify generates a single temp file name per process. The only way I see this happening is to configure where the temp file is saved. Is this a reasonable feature to have?

This has forced me to use gulp builds instead atm.

**Comment by bendrucker** [comment]
I'd really like to confirm that there's no way to do this properly before we add in a config feature that exposes what should be a purely internal concern. Please post the code you're using to call the Karma API.

**Comment by nikku** [comment]
I wonder how this can be possible, after 23a81f3645ce739b5ddc7a0114065d122e75d6cf got merged.

**Comment by simonzack** [comment]
@nikku That fixes the problem of two karmas in separate processes, but if they're within the same process the same `bundleFile` is used in `bro.js`. I understand that this is necessary for a single karma instance since files being served can't change mid-way (unless a temp directory is used).

But karma does appear to support running two instances within the same process. I find this easier as I can just put both test & coverage instances in a single gulp file and run them both. I'll post up my configuration later.

**Comment by bendrucker** [comment]
Yeah using the API is totally valid. So what's going on here is that `bro` is only initialized once (https://github.com/nikku/karma-browserify/blob/master/index.js#L6) and then cached by `require`).

> But karma does appear to support running two instances within the same process.

In reality it doesn't though. As far as I can tell there's no way for us to work around this. Both running karma servers are using the same instance of karma-browserify. Its DI system does the same sort of caching that Node/Browserify do. It's going to call [`framework`](https://github.com/nikku/karma-browserify/blob/master/lib/bro.js#L84-L115) once no matter how many servers you can run and I don't see a way for us to change that.

**Comment by bendrucker** [comment]
I'm not 100% confident in my explanation but it fits with what you're seeing

**Comment by nikku** [comment]
@bendrucker This should very much explain the whole thing.

There might be no way we can pursue karma to bootstrap two karma-browserify instance because we need the distinct combination of framework + preprocessors to actually work.

@simonzack Still interested in your use case.

**Comment by simonzack** [comment]
It's something like this. I've removed the 6to5 parts of my setup to keep it simple.

    // for debugging
    karma.server.start({
      port: 9876,
      frameworks: ['browserify', 'mocha'],
      reporters: ['progress'],
      files: [
        'src/**/*.js',
        'test/**/*.js'
      ],
      preprocessors: {
        'test/**/*.js': ['browserify'],
      },
      browserify: {
        debug: true,
      },
    })

    // coverage
    karma.server.start({
      port: 9877,
      reporters: ['coverage'],
      files: [
        'src/**/*.js',
        'test/**/*.js'
      ],
      preprocessors: {
        'src/**/*.js': ['coverage'],
        'test/**/*.js': ['browserify'],
      },
    });

**Comment by nikku** [comment]
All right. I see what you are doing here. We should be able to support this use case by fixing our bootstrapping code. Will take some time though.

I have opened #105 as a refactoring ticket.

As a workaround you can try to spawn the karma instances via a separate processes.

**Comment by nikku** [comment]
@simonzack Please check if karma-browserify@3.0.3 fixes the problem for you.

**Comment by simonzack** [comment]
@nikku It works now, many thanks!
