### ISSUE TITLE
Creating completely separate bundle files

### ISSUE THREAD

**Issue by wilsonpage** [nikku/karma-browserify#103]
I'm testing `Worker` code and client code. I want to to have two bundles: `worker.js` and `client.js`. Is this possible? From within my suite I want to be able to do:

```js
var worker = new Worker('./path/to/worker.js')
```

**Comment by bendrucker** [comment]
https://www.npmjs.com/package/webworkify

**Comment by wilsonpage** [comment]
I also need this to work for `SharedWorker` and `ServiceWorker`. Is it only possible to have one entry-point/bundle?

**Comment by bendrucker** [comment]
Yes, only one
