### ISSUE TITLE
The bundle isn't written out for the first run causing the tests to fail

### ISSUE THREAD

**Issue by Haegin** [nikku/karma-browserify#108]
I'm trying to use karma-browserify to run my jasmine tests but the bundle isn't generated when the tests run for the first time so it fails with `ReferenceError: Can't find variable: require`.

The full output from `karma start karma.conf.js` is:
```
Writing to file /Users/harry/.tmp/cd7d6d1724ef70d31d4b14e3a25e3945.browserify
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [framework.browserify]: updating spec/attributeSpec.js in bundle
INFO [framework.browserify]: 950882 bytes written (0.90 seconds)
INFO [PhantomJS 1.9.8 (Mac OS X)]: Connected on socket JzUIrXpfhjbDzDoIezMm with id 27220159
PhantomJS 1.9.8 (Mac OS X) ERROR
  ReferenceError: Can't find variable: require
  at /Users/harry/dev/dnd5e/spec/attributeSpec.js:1
PhantomJS 1.9.8 (Mac OS X): Executed 0 of 0 ERROR (0.017 secs / 0 secs)
```

My karma config file is https://github.com/Haegin/dnd5e/blob/10c666eb3211021fbd3e1041bc96cad9bed13e49/karma.conf.js.

I've done some digging and if I change line 196 of `karma-browserify/lib/bro.js` from

 ```javascript
      if (w._builtOnce && !err) {
```

to

```javascript
      if (!err) {
```
everything starts working.

Using `fswatch` to monitor the files in the tmp directory while karma is running shows that without the changes to bro the .browserify file only gets touched to create it and it's never written to. I'm using `fswatch -0 ~/.tmp | xargs -0 -n 1 -I {} ls -l {}` to monitor the changes.

Without the changes:
```
-rw-------  1 harry  staff  0 22 Feb 13:36 /Users/harry/.tmp/f30907c326ccf8c496db4292b7355c9a.browserify
total 8
-rw-------  1 harry  staff  90 22 Feb 13:36 capture.js
-rw-------  1 harry  staff  90 22 Feb 13:36 /Users/harry/.tmp/karma-59765913/capture.js
```
See how the file size (the 5th column) is 0.

After changing bro.js:
```
-rw-------  1 harry  staff  0 22 Feb 13:37 /Users/harry/.tmp/8a6ff9ef9dce187c177fd4fe74ee0a20.browserify
total 8
-rw-------  1 harry  staff  90 22 Feb 13:37 capture.js
-rw-------  1 harry  staff  90 22 Feb 13:37 /Users/harry/.tmp/karma-60105401/capture.js
-rw-------  1 harry  staff  950882 22 Feb 13:37 /Users/harry/.tmp/8a6ff9ef9dce187c177fd4fe74ee0a20.browserify
```
Now the file is still touched to create it at the start but it's also written out later in the process. The test output now reads:

```
Writing to file /Users/harry/.tmp/8a6ff9ef9dce187c177fd4fe74ee0a20.browserify
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [framework.browserify]: updating spec/attributeSpec.js in bundle
INFO [framework.browserify]: 950882 bytes written (0.85 seconds)
Writing to file /Users/harry/.tmp/8a6ff9ef9dce187c177fd4fe74ee0a20.browserify
INFO [framework.browserify]: bundle updated
INFO [PhantomJS 1.9.8 (Mac OS X)]: Connected on socket C8MvJF6TfCCK-1MyggR9 with id 60105401
...
PhantomJS 1.9.8 (Mac OS X): Executed 3 of 3 SUCCESS (0.002 secs / 0.002 secs)
```

Note, I also changed bundle-file.js to log when it writes to the file. You can see this on the first and sixth lines of the output above.

I'm guessing something else should be writing the file on the first bundle and for some reason that isn't happening for me. Is this a bug or do I have something misconfigured?

**Comment by Haegin** [comment]
As another data point, if I change the karma config so it watches the test files then saving the code causes the tests to be run once (correctly) but (probably due to my changes in bro.js I'm guessing), changing a test file causes the tests to be run twice.

**Comment by bendrucker** [comment]
Just cloned your project and you're missing the `reactify` dep. Other than that no issues. `karma start` runs fine. I'm on OS X as well by the way.

**Comment by bendrucker** [comment]
Try `npm i -D reactify && rm -rf node_modules/ && npm i`
