### ISSUE TITLE
Browserify always picks up the same code in Webstorm 9.0.3 (Windows 8.1)

### ISSUE THREAD

**Issue by adamrecsko** [nikku/karma-browserify#109]
# Test project:

https://github.com/adamrecsko/WebstormKarmaCodeChangeWontShowUp

Code changes wont show up in Webstorm karma test runner plugin. Karma caches my the https://github.com/adamrecsko/WebstormKarmaCodeChangeWontShowUp/blob/master/tests/TestFunctionTest.js file.

### How to reproduce:

- Start karma server with karma runner task in Webstorm
- Modify the TestFunctionTest.js file.
- Press play again without restarting karma server.

Change won't show up.

**Comment by bendrucker** [comment]
It's gonna take me some time to get to this since I've gotta go grab a Webstorm trial.

**Comment by nikku** [comment]
The code is running using the command line? Maybe it is advisable to consult the Webstorm support in that matter?

**Comment by adamrecsko** [comment]
From command line it works. The problem appears if I start the tests from Webstorm and use the built in karma runner.

**Comment by bendrucker** [comment]
Now I remember why this seemed familiar: https://github.com/nikku/karma-browserify/issues/23

Unfortunately this is a WebStorm bug which we can't address
