### ISSUE TITLE
TypeError: 'undefined' when using browserify-shim

### ISSUE THREAD

**Issue by mcoetzee** [nikku/karma-browserify#110]
Hi there,

Thanks for all the work on karma-browserify.

I am having problems shimming a global. I have created a small repo that demonstrates the issue here: https://github.com/mcoetzee/shim-example

In essence it boils to down to:
package.json
```
"browserify-shim": {
   "moment": "global:moment"
}
```

karma.conf.js
```
files: [
  "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js",
  '__tests__/**/*.js'
],
```

With this setup, when I point to the CDN, I get:
```
TypeError: 'undefined' is not a constructor (evaluating 'new Moment()')
```

When I change my karma.conf.js like so:
```
files: [
  'libs/moment.min.js',
  '__tests__/**/*.js'
],
```
then the error goes away and my test passes.

Why is it not working when I point to the CDN? I want to use the CDN so that my tests uses the exact same code as in dev/production.

**Comment by nikku** [comment]
Karma does not support resolving files from URLs, i.e. CDNs.

Include moment.js via npm 

```
npm i moment
```

and load it locally

```
files: [
  'node_modules/moment/...'
]
```

**Comment by mcoetzee** [comment]
I'm not too sure about Karma not supporting resolving files from URLs - as I just switched to the karma-firefox-launcher and it worked. It resolved moment from the CDN.
