### ISSUE TITLE
Using browserify 8.0.2 creates an issue with elliptic

### ISSUE THREAD

**Issue by chevdor** [nikku/karma-browserify#111]
See: https://github.com/indutny/elliptic/issues/30#issuecomment-76156429
Taking the latest browserify (9.0.3) fixes the issue above.

**Comment by nikku** [comment]
Feel free to provide a PR that upgrades karma-browserify to the latest version.

**Comment by bendrucker** [comment]
This has gotta go to your fork though

**Comment by nikku** [comment]
Yes, it is a bit more work. We need to make sure our karma-browserify test suite passes on the new browserify@9.x + watchify@3.x combination.

**Comment by chevdor** [comment]
yep, that´s why I would not just patch the number.
Who knows if it does not generate a bunch of issue I have not seen yet.

**Comment by nikku** [comment]
Created an upgrade ticket #112 with a checklist of necessary steps. Feel free to contribute.

**Comment by nikku** [comment]
Fixed via [v4.0.0](https://github.com/nikku/karma-browserify/releases/tag/v4.0.0).
