### ISSUE TITLE
Upgrade to browserify 9.x / watchify 3.x

### ISSUE THREAD

**Issue by nikku** [nikku/karma-browserify#112]
* [ ] Check, whether any of the [workarounds](https://github.com/nikku/node-browserify/tree/karma-browserify) are still needed
* [ ] Port the workarounds to browserify 9.x, if neccessary
* [ ] Bump browserify / watchify versions to latest

**Comment by nikku** [comment]
browserify 9.x properly allows local requires + global exports. Thus we do not need any of our workarounds anymore.

**Comment by bendrucker** [comment]
:tada: 

![party time](http://www.voxmagazine.com/wp-content/uploads/2015/02/giphy.gif)
