### ISSUE TITLE
Issues bundling large project on mac

### ISSUE THREAD

**Issue by TheSavior** [nikku/karma-browserify#119]
We were glad to see 4.1.2 came out with some additional fixes focused on trying to not require the workarounds for mac. (#116, etc).

However, we are still running into the error `require is not defined`

Relevant section:
```
    files: testFiles, // about 100 files
    preprocessors: {
      'app/**/*.js': ['coverage'], // couple hundred files
      'js-tests/src-test/**/*.js': ['browserify'] // couple hundred files
    },
```

A bundle delay of 2000 works for me on my computer with this project, however one of my colleagues needs a bundle delay of 4500 before it starts working.

For both of us, this fix still seems to work: https://github.com/TheSavior/karma-browserify/pull/1 without specifying a bundle delay at all.

We don't want to be using a forked repo to solve this problem, and I understand that this fix can cause some confusing error messages in a few states.

I don't think further increasing the bundle delay is the right solution since it is inherently flaky and wholly dependent on the size of the project. Is there any way to add a bit more logic to the fix in the PR such that it won't hide easier to understand error messages, but will improve the behavior for waiting for files?

**Comment by bendrucker** [comment]
Out of curiosity, are you and/or your colleague using an SSD? We should fix this issue at the root but I am interested to know why the symptoms vary so considerably.

**Comment by TheSavior** [comment]
I'm on a 15" Macbook Pro, he is on a 13" Macbook Pro, both with SSDs.

**Comment by bendrucker** [comment]
Bizarre. No idea why the discrepancy would be so huge with similar hardware.

**Comment by nikku** [comment]
A colleague of mine had the bundle delay fixes event though he was using an SSD, too. His problems are fixed though with the latest version of karma-browserify.

We are working on a code base with 104+ (lib) and 74+ (test) files respectively without problems.

The only thing I can think of is some sort of interaction between the coverage preprocessor and karma-browserify. Try to switch to [browserify-istanbul](https://www.npmjs.com/package/browserify-istanbul) and see if it resolves your issues.

**Comment by TheSavior** [comment]
We've turned off coverage completely to no change. :-(

**Comment by nikku** [comment]
Too bad that did not do the trick. Unfortunately I see no way we can reproduce this issue.

Feel free to reopen your bug if you set up an example project that shows the expected behavior. In the mean time, you'd need to rely on your fork.
