### ISSUE TITLE
Tests only pass after the second bundle in Firefox

### ISSUE THREAD

**Issue by jasonslyvia** [nikku/karma-browserify#120]
This is strange behaviour but I do reproduce it in OS X and Linux(Travis CI).

**How to reproduce**

1. clone [https://github.com/jasonslyvia/react-anything-sortable](https://github.com/jasonslyvia/react-anything-sortable)
2. `$ npm install`
3. `$ npm run test`
4. Firefox fails 4 tests and Chrome pass all
5. In text editor, save `/test/specs/test.js`, makes no change
6. After rebundle, both Firefox and Chrome pass all tests

**Environment Info**

OS: OS X 10.10.2 (14C109)
Browser: Firefox 35.0.1
Karma: 0.12.31
karma-browserify: 4.1.2

**Console Output**

npm run test

> react-anything-sortable@0.2.0 test /Code/react-anything-sortable
> ./node_modules/karma/bin/karma start test/karma.conf.js

DEBUG [plugin]: Loading karma-* from /Code/react-anything-sortable/node_modules
DEBUG [plugin]: Loading plugin /Code/react-anything-sortable/node_modules/karma-browserify.
DEBUG [plugin]: Loading plugin /Code/react-anything-sortable/node_modules/karma-chai.
DEBUG [plugin]: Loading plugin /Code/react-anything-sortable/node_modules/karma-chrome-launcher.
DEBUG [plugin]: Loading plugin /Code/react-anything-sortable/node_modules/karma-coverage.
DEBUG [plugin]: Loading plugin /Code/react-anything-sortable/node_modules/karma-firefox-launcher.
DEBUG [plugin]: Loading plugin /Code/react-anything-sortable/node_modules/karma-mocha.
DEBUG [plugin]: Loading plugin /Code/react-anything-sortable/node_modules/karma-phantomjs-launcher.
DEBUG [plugin]: Loading plugin /Code/react-anything-sortable/node_modules/karma-safari-launcher.
DEBUG [framework.browserify]: created browserify bundle: /var/folders/pm/r2vxfb3s2csgbxf2knv_08qm0000gn/T/a48e86d51ce69260d270ea4ee5bba5a8.browserify
INFO [framework.browserify]: registering rebuild (autoWatch=true)
DEBUG [framework.browserify]: add bundle to config.files at position 4
WARN [karma]: Port 9876 in use
INFO [karma]: Karma v0.12.31 server started at http://localhost:9877/
INFO [launcher]: Starting browser Firefox
DEBUG [temp-dir]: Creating temp dir at /var/folders/pm/r2vxfb3s2csgbxf2knv_08qm0000gn/T/karma-47652026
DEBUG [launcher]: /Applications/Firefox.app/Contents/MacOS/firefox-bin http://localhost:9877/?id=47652026 -profile /var/folders/pm/r2vxfb3s2csgbxf2knv_08qm0000gn/T/karma-47652026 -no-remote
DEBUG [framework.browserify]: building bundle
DEBUG [framework.browserify]: updating test/specs/test.js in bundle
DEBUG [web-server]: serving: /Code/react-anything-sortable/node_modules/karma/static/client.html
DEBUG [framework.browserify]: bundling
DEBUG [web-server]: serving: /Code/react-anything-sortable/node_modules/karma/static/karma.js
DEBUG [web-server]: upgrade /socket.io/1/websocket/mTEnfZf3tY-gvst1Pgzq
DEBUG [karma]: A browser has connected on socket mTEnfZf3tY-gvst1Pgzq
INFO [Firefox 35.0.0 (Mac OS X 10.10)]: Connected on socket mTEnfZf3tY-gvst1Pgzq with id 47652026
DEBUG [launcher]: Firefox (id 47652026) captured in 2.407 secs
DEBUG [karma]: All browsers are ready, executing
INFO [framework.browserify]: 2073611 bytes written (6.13 seconds)
INFO [framework.browserify]: bundle built
DEBUG [watcher]: Resolved files:
	/Code/react-anything-sortable/node_modules/chai/chai.js
	/Code/react-anything-sortable/node_modules/karma-chai/adapter.js
	/Code/react-anything-sortable/node_modules/mocha/mocha.js
	/Code/react-anything-sortable/node_modules/karma-mocha/lib/adapter.js
	/var/folders/pm/r2vxfb3s2csgbxf2knv_08qm0000gn/T/a48e86d51ce69260d270ea4ee5bba5a8.browserify
	/Code/react-anything-sortable/test/specs/test.js
	/Code/react-anything-sortable/demo/style.css
DEBUG [watcher]: Watching "/var/folders/pm/r2vxfb3s2csgbxf2knv_08qm0000gn/T/a48e86d51ce69260d270ea4ee5bba5a8.browserify"
DEBUG [watcher]: Watching "/Code/react-anything-sortable/test/specs/test.js"
DEBUG [watcher]: Watching "/Code/react-anything-sortable/demo/style.css"
DEBUG [web-server]: serving: /Code/react-anything-sortable/node_modules/karma/static/context.html
DEBUG [web-server]: serving (cached): /Code/react-anything-sortable/node_modules/chai/chai.js
DEBUG [web-server]: serving (cached): /Code/react-anything-sortable/node_modules/karma-chai/adapter.js
DEBUG [web-server]: serving (cached): /Code/react-anything-sortable/node_modules/mocha/mocha.js
DEBUG [web-server]: serving (cached): /Code/react-anything-sortable/node_modules/karma-mocha/lib/adapter.js
DEBUG [web-server]: serving (cached): /var/folders/pm/r2vxfb3s2csgbxf2knv_08qm0000gn/T/a48e86d51ce69260d270ea4ee5bba5a8.browserify
DEBUG [web-server]: serving (cached): /Code/react-anything-sortable/test/specs/test.js
Firefox 35.0.0 (Mac OS X 10.10): Executed 0 of 9 SUCCESS (0 secs / 0 secs)
Firefox 35.0.0 (Mac OS X 10.10) Sortable Dragging children should switch position when dragging from left to right FAILED
	expected '3' to equal '1'
Firefox 35.0.0 (Mac OS X 10.10) Sortable Dragging children should switch position when dragging from right to left FAILED
	expected '1' to equal '3'
Firefox 35.0.0 (Mac OS X 10.10) Sortable onSort Props should call onSort when a drag'n'drop finished FAILED
	expected { Spy, 1 call } to have been called with [ [ '2', '3', '1' ] ]
Firefox 35.0.0 (Mac OS X 10.10) Sortable onSort Props should call onSort when a opposite drag'n'drop finished FAILED
	expected { Spy, 1 call } to have been called with [ [ '3', '1', '2' ] ]
Firefox 35.0.0 (Mac OS X 10.10): Executed 9 of 9 (4 FAILED) (0.08 secs / 0.044 secs)
DEBUG [coverage]: Writing coverage to /Code/react-anything-sortable/test/coverage
------------------|-----------|-----------|-----------|-----------|
File              |   % Stmts |% Branches |   % Funcs |   % Lines |
------------------|-----------|-----------|-----------|-----------|
   demo/          |       100 |        75 |       100 |       100 |
      DemoItem.js |       100 |        75 |       100 |       100 |
   src/           |     75.74 |     57.33 |     66.67 |     75.64 |
      index.js    |     79.74 |     66.35 |     70.59 |     79.61 |
      utils.js    |     68.29 |     36.96 |     58.82 |     68.29 |
------------------|-----------|-----------|-----------|-----------|
All files         |     76.83 |     57.79 |     68.52 |     76.64 |
------------------|-----------|-----------|-----------|-----------|

INFO [watcher]: Changed file "/Code/react-anything-sortable/test/specs/test.js".
DEBUG [framework.browserify]: updating test/specs/test.js in bundle
DEBUG [framework.browserify]: files changed
DEBUG [framework.browserify]: resetting bundle
DEBUG [framework.browserify]: bundling
INFO [framework.browserify]: 2073611 bytes written (0.89 seconds)
INFO [framework.browserify]: bundle updated
DEBUG [karma]: List of files has changed, trying to execute
DEBUG [karma]: All browsers are ready, executing
INFO [watcher]: Changed file "/var/folders/pm/r2vxfb3s2csgbxf2knv_08qm0000gn/T/a48e86d51ce69260d270ea4ee5bba5a8.browserify".
DEBUG [web-server]: serving (cached): /Code/react-anything-sortable/node_modules/karma/static/context.html
DEBUG [web-server]: serving (cached): /Code/react-anything-sortable/demo/style.css
Firefox 35.0.0 (Mac OS X 10.10): Executed 9 of 9 SUCCESS (0.085 secs / 0.045 secs)
DEBUG [coverage]: Writing coverage to /Code/react-anything-sortable/test/coverage
------------------|-----------|-----------|-----------|-----------|
File              |   % Stmts |% Branches |   % Funcs |   % Lines |
------------------|-----------|-----------|-----------|-----------|
   demo/          |       100 |        75 |       100 |       100 |
      DemoItem.js |       100 |        75 |       100 |       100 |
   src/           |     79.15 |        62 |     68.63 |     79.06 |
      index.js    |     84.97 |     73.08 |     73.53 |     84.87 |
      utils.js    |     68.29 |     36.96 |     58.82 |     68.29 |
------------------|-----------|-----------|-----------|-----------|
All files         |     80.08 |     62.34 |     70.37 |     79.92 |
------------------|-----------|-----------|-----------|-----------|

**Comment by nikku** [comment]
This is a timing related issue. You are [loading a CSS file](https://github.com/jasonslyvia/react-anything-sortable/blob/master/test/specs/test.js#L203) that will not yet be available in the document at the time the test case runs for the first time.

Commenting out the [`insertCSS`](https://github.com/jasonslyvia/react-anything-sortable/blob/master/test/specs/test.js#L211) call causes four test cases in both browsers to fail consistently.

**Comment by jasonslyvia** [comment]
That's awesome, thanks for pointing it out!
