### ISSUE TITLE
Support Browserify external option?

### ISSUE THREAD

**Issue by jbalboni** [nikku/karma-browserify#123]
I was wondering if support could be added for using external bundles. I have a set of applications that depend on a common set of bundles. When we build these applications using grunt-browserify, we use the external property so that we can build the common bundles separately.

So I'm looking for something like what grunt-browserify does with the external property in the options object. It looks pretty simple to add; I was able to add a line to bro.js to make the external() call on the watchify bundle and it seems to work.

I can submit a PR if this something that you want to support.

**Comment by bendrucker** [comment]
You can do this via `configure`. The only things that get special handling are transforms and plugins. We're not going to add more. The goal is to make the most common features easy but leave everything else to code.

**Comment by jbalboni** [comment]
Oh, I didn't realize I could do that through configure. That's perfectly fine for me. Thanks!
