### ISSUE TITLE
coffeeify transform running twice.

### ISSUE THREAD

**Issue by seanhealy** [nikku/karma-browserify#130]
Hey,

I'm seeing an issue where the `coffeeify` transform is running twice.

Here is a snip from my `karma.conf.coffee`

```coffeescript
    browserify:
        debug: true
        watch: true
        extensions: ['.coffee']
        transform: ['coffeeify']
        configure: (bundle) ->
            bundle.transform coverage
                ignore: [
                  ...
                ]
                defaultIgnore: true
```

I have specified it in my `package.json` to notify apps using my module that it needs to be coffeeify-ed. However when I do this I see the following error:

```
ERROR [framework.browserify]: bundle error
ERROR [framework.browserify]: /path/to/index.coffee:2
var __cov_kd5zAv9pEtVVtEp6AC53kQ = (Function('return this'))();
^
ParseError: reserved word 'var'
```

If I then remove the `coffeeify` transform from the `browserify` section of my karma conf it will then not run the transform at all and I see the following error:

```
ERROR [framework.browserify]: bundle error
ERROR [framework.browserify]: Error: Line 1: Unexpected string while parsing file: /path/to/index.coffee
```

I'm likely missing something obvious here but I've been stumped on this for a while here…

Thanks!
Sean

**Comment by bendrucker** [comment]
Need something minimal I can clone and run to look any further. Also please write the Karma config file in the reproduction repo in plain JS.

**Comment by pdufour** [comment]
having same issue. @seanhealy if you are interested in a temporary fix: https://github.com/britco/coffeeify/commit/eb89a850f2e47eee029c386d8a8eec397021b4fa. not sure if this is the right place to fix it or not, i understand browserify but i don't really know karma that well.

**Comment by bendrucker** [comment]
No, that's not the right place to fix it.

**Comment by nikku** [comment]
Could you provide us with an example we can look into that reproduces the issue?

**Comment by everyonesdesign** [comment]
I faced the same issue using browserify
if I use 'browserify' transform in package.json and in karma.conf it will be applied twice during testing.

**Comment by everyonesdesign** [comment]
it seems that the situation happens because of browserify itself.
in method [Browserify.prototype._createDeps](https://github.com/substack/node-browserify/blob/master/index.js#L419) it uses 'module-deps' module [to locate package.json file](https://github.com/substack/module-deps/blob/master/index.js#L444).
I think it finally somehow uses it to run transforms located here. But it shouldn't, cause the options we define in karma.conf should have higher priority

**Comment by everyonesdesign** [comment]
@seanhealy @bendrucker @pdufour @nikku 
OK, i found a funny workaround for the issue now but it's a kludge really.
we need to trick 'module-deps' and tell it not to use transforms from our package.json.
we can see [here](https://github.com/substack/node-browserify/blob/master/index.js#L432) that browserify applies transforms from package.json in postFilter callback. 
we can use the condition `if (opts.postFilter && !opts.postFilter(id, file, pkg)) return false;` to cancel transforms usage if our package.json is used.
if you print something like this
```javascript
    browserify: {
        postFilter: function(id, file, pkg) {
            if (pkg.name == '*your package name from package.json*') {
                pkg.browserify.transform = [];
            }
            return true;
        },
        transform: ['stringify', 'browserify-istanbul']
    },
```
in your karma.conf.js, karma browserify will use only transforms written here.

I guess, to fix this problem in correct way we need to change a bit browserify api somehow.

**Comment by nikku** [comment]
Thanks for the workaround.

**Comment by seanhealy** [comment]
We just got back to this and the fix seems to work. Thanks!

**Comment by mediafreakch** [comment]
@nikku Is this a bug that should be fixed? If yes, where?

**Comment by nikku** [comment]
@mediafreakch Did you discover a bug? Please open a new bug ticket with exact steps to reproduce the issue you found (i.e. an example project somewhere on GitHub).
