### ISSUE TITLE
Browserify feeding a mix of relative and absolute paths to coverage, causing problems with html reporting.

### ISSUE THREAD

**Issue by pleunv** [nikku/karma-browserify#131]
I'm having some issues with a combination of Karma - Mocha - ES6 - React - Browserify - Istanbul. OS is Windows, which might or might not be related.
Karma-browserify seems to be feeding a mix of absolute and relative paths to coverage, as far as I can see coverage cannot deal with the absolute paths.

My Karma config is as follows:

```
function getKarmaConfig() {
    var config = {
        files: [
            '../../node_modules/phantomjs-polyfill/bind-polyfill.js',
            '**/tests/*-tests.js',
            '**/tests/*-tests.jsx'
        ],
        exclude: [],
        coverage: {
            dir: './report/coverage',
            reporters: [
                { type: 'html', subdir: 'report-html' },
                { type: 'text-summary' }
            ]
        },
        browserify: {
            debug: true,
            transform: ['babelify', istanbul({
                ignore: ['../../node_modules/**']
            })],
            extensions: ['.jsx']
        },
        preprocessors: {
            '**/tests/*-tests.js': ['browserify', 'coverage'],
            '**/tests/*-tests.jsx': ['browserify', 'coverage']
        }
    };

    return config;
}
```

My project structure is something like this:

```
libs\<moduleName>\<componentName>\<componentName>.js
libs\<moduleName>\<componentName>\tests\<componentName>-tests.js
```

Browserify is (I assume) preprocessing the test files, resolving the imports, adding those to the collection and passing them to coverage.
When I log the file collection that istanbul is receiving I get the following:

```
key: ./libs/ui-modules/Rating/tests/Rating-tests.jsx
key: C:\Projects\React\prototype-react\src\client\libs\ui-modules\Rating\Rating.jsx
key: C:\Projects\React\prototype-react\src\client\libs\ui-modules\Rating\Star.jsx
key: ./libs/ui-modules/Tabs/tests/Tabs-tests.jsx
key: C:\Projects\React\prototype-react\src\client\libs\ui-modules\index.js
key: C:\Projects\React\prototype-react\src\client\libs\ui-modules\Tabs\Tab.js
key: C:\Projects\React\prototype-react\src\client\libs\ui-modules\Tabs\TabContainer.js
key: C:\Projects\React\prototype-react\src\client\libs\ui-modules\Tabs\TabList.js
key: C:\Projects\React\prototype-react\src\client\libs\ui-modules\Tabs\TabPanel.js
key: C:\Projects\React\prototype-react\src\client\libs\ui-modules\Tabs\TabPanelList.js
```

The files that can be directly looked up by the glob pattern are added as a **relative** path, import statements that are looked up by browserify are added with an **absolute** path. Istanbul can generate html coverage from the relative paths, however it appears to be unable to resolve the absolute ones, resulting in the following error(s):

```
TypeError: Cannot read property 'split' of undefined
    at HtmlReport.Report.mix.writeDetailPage (C:\Projects\React\prototype-react\node_modules\istanbul\lib\report\html.js:397:30)
```

Is this an issue with the Browserify path resolving? Should everything be relative by default, or is this rather something that Istanbul should be able to remediate?
I'm also not sure if I should report this on the karma, browserify, karma-browserify or istanbul repo, so I guess I'll start here :)

**Comment by nikku** [comment]
You need to use a browserify transform to instrument + retrieve the coverage data, i.e. [browserify-istanbul](https://github.com/devongovett/browserify-istanbul).
