### ISSUE TITLE
Example stops working when using a hidden TMPDIR (i.e. dir starting with a dot)

### ISSUE THREAD

**Issue by alimfeld** [nikku/karma-browserify#134]
To reproduce clone the repo and issue the following commands (tested on a Mac and a Linux box):
```bash
$ cd karma-browserify/example
$ mkdir /tmp/.tmp
$ export $TMPDIR=/tmp/.tmp
$ npm install
$ npm test
```
The tests fail with `ReferenceError: Can't find variable: require`
It seems like the file created by Browserify is not served properly (no content).
Not sure whether this is a karma-browserify issue or a karma issue. Any idea what's going wrong here?

**Comment by nikku** [comment]
Not sure what the problem is here. I am pretty sure it is no karma-browserify issue though.
