### ISSUE TITLE
Reactify transformation is not done.

### ISSUE THREAD

**Issue by iLikeKoffee** [nikku/karma-browserify#135]
Hello, I'm using karma-browserify to test a project, written in ReactJS using .JSX syntax. When i try to require some plain js module in tests, it's importing fine, but when jsx file is imported, Bundler error is thrown.

See [SO Question](http://stackoverflow.com/questions/31098968/karma-browserify-transformations-are-not-done) for details and karma config.

Please, tell me what I'm doing wrong.

P.S. Thank you very much in advance.

**Comment by bendrucker** [comment]
Please don't double post questions in the future. We need a full reproducible example to look at this. That  means that I should be able to write `npm install && npm test` and have it exit with 1. No gulp/grunt or really anything but karma, reactify, and a source file please.

**Comment by iLikeKoffee** [comment]
Sorry, just forgot to include plugin. I thought that is a common issue. I should stop working on Sundays.

P.S. Sorry for doubling post.
