### ISSUE TITLE
Investigate test suite failures

### ISSUE THREAD

**Issue by nikku** [nikku/karma-browserify#138]
Users report a number of strange issues that may relate to the latest version bump in karma (#133).

This results in parts of the test suite being broken too. Needs investigation.

**Comment by jayfunk** [comment]
I appear to still have this issue. I am using karma-browserify 4.3.0 and I have installed karma 0.13.10. Any ideas?

**Comment by nikku** [comment]
More hints on the issues you are seeing and steps how to reproduce would be fantastic!
