### ISSUE TITLE
Unknown provider

### ISSUE THREAD

**Issue by DrogoNevets** [nikku/karma-browserify#141]
I am trying to write a simple test as boiler plate, having never used browserify before. 

My skeleton app is working fine, so am reluctant to change anything there.

My test looks like

    'use strict';
    require('angular');
    require('angular-mocks');

    describe('app module', function () {
        var $controller, ctrl;

        beforeEach(function () {
            angular.mock.module(require('./softphone.controller').name);
        });

        // DOES NOT WORK
        beforeEach(angular.mock.inject(function ($injector) {
            ctrl = $injector.get('aahSoftphoneController');
        }));

        // DOES NOT WORK
        beforeEach(angular.mock.inject(function (aahSoftphoneController) {
            ctrl = aahSoftphoneController;
        }));

        // WORKS BUT WILL BREAK FOR SERVICES, ETC
        beforeEach(angular.mock.inject(function (_$controller_) {
            $controller = _$controller_;
            ctrl = $controller('aahSoftphoneController');
        }));

        beforeEach(function () {
            // Add directive variables
            ctrl.width = 2;
            ctrl.offset = 10;
        });

        it('should assert that 1 is indeed 1', function () {
            expect(ctrl.getOffset()).toBe(10);
        });
    });

i would normally, to get hold of the controller simply do
    
    inject(function(myController) { ... })
     

But that seems to not be working within our tests now we've started using browserify. What is it I am doing wrong?

**Comment by bendrucker** [comment]
Sorry, this is definitely not a karma-browserify issue. This depends entirely on the contents of the `'./softphone.controller'` module.

**Comment by DrogoNevets** [comment]
Ok maybe it isn't but there seems to be no documentation as to how to get the tests working. Anywhere.

If I don't use browserify, this works fine. SO what I am asking for is help, and maybe some documentation on how to write tests for karma using the plugin. You say how to edit karma config, but not the tests themselves
