### ISSUE TITLE
Standalone

### ISSUE THREAD

**Issue by garygreen** [nikku/karma-browserify#145]
Is it possible to configure standalone? 

>  --standalone -s  Generate a UMD bundle for the supplied export name.
                   This bundle works with other module systems and sets the name
                   given as a window global if no module system is found.

**Comment by bendrucker** [comment]
Other than a list of options that are handled specially, everything is passed to browserify

https://github.com/nikku/karma-browserify/blob/c32def32d076ea7335f63933152f4b40354f8cdb/lib/bro.js#L176

**Comment by axelpale** [comment]
See available options and their values here: https://github.com/substack/node-browserify#browserifyfiles--opts

Example:

    browserify: {
        debug: true,
        standalone: mylib
    }

However, I have no idea where the file `mylib.js` will be stored.
