### ISSUE TITLE
Transforms get applied twice

### ISSUE THREAD

**Issue by mediafreakch** [nikku/karma-browserify#152]
Hello,

Following up on the discussions in #130 I created an example to reproduce the issue of browserify transforms that get applied twice.

In the example I declared the transform once inside the `package.json` and also within `karma.conf.js` (which might be needed if you require a file to transform directly inside a test).

You can clone the repository here: https://github.com/mediafreakch/karma-browserify-bug
Follow the steps in the README to reproduce.

If you remove either the transform configuration inside `karma.conf.js` or `package.json`, the test will pass.

**Comment by bendrucker** [comment]
Yes, that's how browserify works. If you specify transforms in your package and then apply the same ones via the API, they run 2x.
