### ISSUE TITLE
Is it possible to use the `require` browserify option?

### ISSUE THREAD

**Issue by rapzo** [nikku/karma-browserify#155]
From what i understood from the code it isn't... Hope i'm wrong.
Basically what i was looking for was aliasing the required path which can be done with:
```
var b = browserify({
...
require: [{ file: 'full/path/file.js', expose: 'file' }]
...
});
```
Thanks in advance.

**Comment by rapzo** [comment]
To add a little bit more, i tried with this in the karma.conf.js file:
```
...
browserify: {
  configure: function (bundle) {
    bundle.on('prebundle', function () {
      bundle.require({ file: path.join('.', '.tmp', 'scripts', 'templates.js'), expose: 'templates'});
    });
}
...
```
But it doesn't resolve... Any pointers are welcome :-)

**Comment by nikku** [comment]
It is not possible to do this. Each required path will be aliased to the absolute path per default.
