### ISSUE TITLE
Syntax error is not reported explicitly where is located

### ISSUE THREAD

**Issue by hackhat** [nikku/karma-browserify#162]
Syntax error is not reported explicitly where is located

		DEBUG [web-server]: serving: C:\***\node_modules\karma\static/context.html
		PhantomJS 1.9.8 (Windows 7) ERROR
		  TEST RUN WAS CANCELLED because this file contains some errors:
		    C:/Users/***/AppData/Local/Temp/4cd6770aa5a637b8b76ac0311ce87113.browserify
		    

Example.js

     someFn({a}, b: 'c');

**Comment by nikku** [comment]
This may be due to Browserify not generating source maps for files with syntax errors.

**Comment by nikku** [comment]
Reproducing the issue against the latest karma-browserify, it looks like we properly display the error during compile (which should be enough for a user to fix it):

```
19 01 2016 09:10:59.626:DEBUG [framework.browserify]: building bundle
19 01 2016 09:10:59.627:DEBUG [framework.browserify]: updating test/syntax-error/errorSpec.js in bundle
19 01 2016 09:10:59.629:DEBUG [framework.browserify]: updating test/syntax-error/requireErrorSpec.js in bundle
19 01 2016 09:11:00.339:DEBUG [framework.browserify]: bundling
19 01 2016 09:11:00.401:ERROR [framework.browserify]: bundle error
19 01 2016 09:11:00.402:ERROR [framework.browserify]: 
/home/nikku/Projects/karma-browserify/test/integration/test/syntax-error/errorSpec.js:2
someFn({a}, b: 'c');
             ^
ParseError: Unexpected token
```

Please give us additional details when this occurs to you.

**Comment by nikku** [comment]
Will reopen this if you give us further details on the issue.
