### ISSUE TITLE
babel presents

### ISSUE THREAD

**Issue by select** [nikku/karma-browserify#163]
I am trying to make browserify transforms with babelify work, but I do not understand how to pass in the `es2015` `presents` option. In other configurations I have seen this:
```
browserify: {
      debug: true,
      transform: [ 'babelify',{
        presets: ['es2015']
      } ]
    },
```
this however causes an error in `async.js` `[framework.browserify]: Error: path must be a string`. Is there a way to make it work?

**Comment by TheSavior** [comment]
Have you tried specifying babel transforms in the `.babelrc` file?

**Comment by bendrucker** [comment]
That's not the correct syntax. `transform` itself is an array so you'll need this:

```js
browserify: {
  debug: true,
  transform: [
    ['babelify',{
      presets: ['es2015']
    }]
  ]
}
```

**Comment by select** [comment]
@bendrucker  thanks :D
