### ISSUE TITLE
karma-browserify coverage reports contain file include paths instead of source code

### ISSUE THREAD

**Issue by bshack** [nikku/karma-browserify#166]
Using karma-browserify to do unit tests with Jasmine. The tests correctly run but the coverage reports show file include paths instead of source code. You can reproduce this by installing the following project and run 'gulp unit':

https://github.com/bshack/shackstack

Here is an example of the coverage report contents:

    typeof require === "function" && require("/xxx/xxx/xxx/shackstack/app/media/script/service/utilities.js");

Here is my karma.config:

    module.exports = function(karma) {
        'use strict';
        karma.set({
            basePath: '',
            frameworks: [
                'jasmine',
                'browserify'
            ],
            files: [{
                pattern: 'app/media/script/service/*.js',
                included: true
            },
            {
                pattern: 'app/media/test/spec/*Spec.js',
                included: true
    
            }],
            reporters: [
                'progress',
                'coverage'
            ],
            preprocessors: {
                'app/media/script/service/*.js': [
                    'browserify',
                    'coverage'
                ],
                'app/media/test/spec/*Spec.js': [
                    'browserify'
                ]
            },
            browsers: [
                //'Chrome',
                //'Firefox',
                //'Safari',
                'PhantomJS'
            ],
            singleRun: false,
            autoWatch: false,
            // browserify configuration
            browserify: {
                debug: true,
                transform: [
                    'brfs',
                    'browserify-shim'
                ]
            },
            coverageReporter: {
                type: 'html',
                dir: 'app/report/istanbul/',
                subdir: '.'
            },
            // If browser does not capture in given timeout [ms], kill it
            captureTimeout: 60000
        });
    };

any thoughts?

Asked this on stackoverflow too:

http://stackoverflow.com/questions/35122592/karma-browserify-coverage-reports-contain-file-include-paths-instead-of-source-c

**Comment by nikku** [comment]
* Do not include your app files, include only your test files instead.
* Use a browserify transform for coverage instrumentation (i.e. [browserify-istanbul](https://github.com/devongovett/browserify-istanbul)) and not a Karma plug-in.

**Comment by gaggle** [comment]
@nikku FYI I could not get it working by only including test files.

[This blog](https://jaredtong.com/2016/01/08/how-to-set-up-mocha-chai-sinon-karma-browserify-istanbul-codecov/) suggests doing the opposite, and its made my Karma output valid coverage. In it @tongrhj includes test- and src-files separately, and transforms browserify via the `browserify-istanbul` library you also linked.
