### ISSUE TITLE
Karma runs 0 tests

### ISSUE THREAD

**Issue by ri0ter** [nikku/karma-browserify#169]
Everytime I run a test it gives me this message: ` Executed 0 of 0 ERROR (0.003 secs / 0 secs)`.
This is my config:
```
module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['browserify','chai','mocha'],


    // list of files / patterns to load in the browser
    files: [
      'test/*.js'
    ],


    // list of files to exclude
    exclude: [
    ],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
      'test/*.js': ['browserify']
    },

    /*browserify: {
      debug: true
    },*/


    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['mocha'],


    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_DEBUG,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: false,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: [],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false,

    // Concurrency level
    // how many browser should be started simultaneous
    concurrency: Infinity
  })
}
```

So I've tried to debug this problem, and first thing I've noticed was the empty `*.browserify` file in the `/tmp/` directory. I've found out that when I commented out this line - https://github.com/nikku/karma-browserify/blob/master/lib/bro.js#L386 everything was fine.
It seems that it falls into this condition https://github.com/nikku/karma-browserify/blob/master/lib/bro.js#L377 and the browserify gets empty content.

**Comment by nikku** [comment]
What should happen in the combination `singleRun: false` and `autoWatch: false`?

**Comment by ri0ter** [comment]
I'm using some external tool which starts karma server and runs test only in some particular situations. 
But if one options excludes the other (which is not obvious), than maybe there should be some kind of a warning when runing server, or just a comment somewhere in the config?

**Comment by nikku** [comment]
Even when having the external tool, you probably want `auto-watch: true`. Or does the external tool perform the watching for you?

**Comment by ri0ter** [comment]
The tool triggers everything for me.
Btw... this issue seems to be similar to https://github.com/nikku/karma-browserify/issues/167

**Comment by nikku** [comment]
Changing the line you mentioned above to `b._builtOnce = config.autoWatch;` fixes the issue.

I'll ship a fix as soon as I am able to reproduce that as part of a test case.
