### ISSUE TITLE
Watchify as optional dependency?

### ISSUE THREAD

**Issue by TheSavior** [nikku/karma-browserify#171]
I never want to use autoWatch: true, and thus don't want to have watchify in my devDeps. Is it reasonable for karma-browserify to use it as an optional dependency?

**Comment by bendrucker** [comment]
Sure, but how would that help? It's still going to be installed anyway, the only difference would be that your build wouldn't fail if the `npm install` of just watchify failed.

**Comment by nikku** [comment]
Isn't `npm@3` warning, if you do not have watchify and then it allows you to continue anyway?

**Comment by nikku** [comment]
I'd argue most people actually do watch. One indication is: Only today did I close a bug that prevented `singleRun=false` to work without `autoWatch=true` (cf. #169).

So judging by that we are going to call big confusion dropping it.

Any particular reasons you _do not want to have watchify in [your] devDeps_?

**Comment by TheSavior** [comment]
I don't want to have it in my devDeps because I know it will never be used and thus it is just bloat to my project and another dependency that I have to worry about going out of date. *shrug*

**Comment by bendrucker** [comment]
Ok, but that's not how `optionalDependencies` work. That just means that the install can fail and the build doesn't fail. Closing.
