### ISSUE TITLE
Allow by configuration to keep bundles for future use

### ISSUE THREAD

**Issue by dendril** [nikku/karma-browserify#174]
Hey,

I'm running in some issues and found no way to keep the bundles ran into the browser to be analysed. Could be possible to make the bundle clean up to be conditional?

Let me know if doesn't make sense to allow this, in the meantime I'm looking for an alternative for manual testing.

Thanks!

**Comment by bendrucker** [comment]
Don't think this really makes a lot of sense. You can just enable a high enough log level to get the path and then copy the bundle.

**Comment by TheSavior** [comment]
@bendrucker Doesn't karma clean up and delete the tmp directories, which include the bundles, after the run?

**Comment by bendrucker** [comment]
Right, so the idea would be to use autoWatch and then grab the bundle while the build is waiting

**Comment by dendril** [comment]
@bendrucker I been trying to do that, but no worries, I'll handle that by myself if it's too much work and and `if` statement in the code.

**Comment by nikku** [comment]
@dendril You are free to propose your changes as part of well documented and tested PR. That makes it easier to get your feature into the code base :wink:.
