### ISSUE TITLE
Support browserify wrappers like browserify-incremental

### ISSUE THREAD

**Issue by olegskl** [nikku/karma-browserify#176]
I would like to use [browserify-incremental](https://github.com/jsdf/browserify-incremental) or similar wrapper for caching build results.

**Comment by olegskl** [comment]
Actually... it should work as is already. Investigating...

**Comment by nikku** [comment]
Is there anything we need to do here?

**Comment by olegskl** [comment]
Probably not, unless you want to add a way to rewrite the `w` variable via `configure` method. I have opened https://github.com/jsdf/browserify-cache-api/pull/8 which seems to be a sufficient for my needs.

**Comment by TheSavior** [comment]
@olegskl How did you get this working? Can you provide an example for me and future people in the same situation?

**Comment by olegskl** [comment]
@TheSavior I'm using this: https://github.com/olegskl/browserify-cache-api/tree/resume-bundlestream
