### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by scaljeri** [nikku/karma-browserify#180]
When I try to test my [project](https://github.com/scaljeri/javascript-dependency-injection) I get the following error in the browser

     jasmine.js:796 Uncaught TypeError: Cannot read property 'length' of undefined

I've tried to tweak the `preprocessors` section of the karma conf

        preprocessors: {
            './di.js': ['coverage', 'browserify'],
            './tests/di.spec.js': ['browserify']
        },

 but the end result is always the same
To run the test do:

    $> git clone https://github.com/scaljeri/javascript-dependency-injection.git
    $> npm install
    $> gulp test

![image](https://cloud.githubusercontent.com/assets/1078741/14507911/3f1b90d4-01c5-11e6-831e-1a230ac4b4af.png)

Any suggestion what might be the problem ?

**Comment by nikku** [comment]
Problem: You are missing a description as [part of your spec](https://github.com/scaljeri/javascript-dependency-injection/blob/master/tests/di.spec.js#L3):

```javascript
describe('something', function() {
  // specs go here
});
```

**Comment by scaljeri** [comment]
How stupid, thanks for pointing that out!
