### ISSUE TITLE
Suppress missing watchify errors

### ISSUE THREAD

**Issue by gaggle** [nikku/karma-browserify#181]
`watchify` is an optional dependency, but I always see errors due to [bro.js](https://github.com/nikku/karma-browserify/blob/master/lib/bro.js):

    try {
      watchify = require('watchify');
    } catch (e) {
      console.error('watchify not found; install it via npm install --save-dev watchify');
      console.error('incremental rebuild will be disabled');
    }

But a lack of watchify isn't an error for me. Would you consider a way to suppress them? Maybe something like `watchify: false` in karma conf?

**Comment by nikku** [comment]
Good point! I'd print the warning if the user uses `watch: true` without watchify installed only.

That would solve the issue, right?
