### ISSUE TITLE
reactify or babelify transform doesn't work after v4.4.2

### ISSUE THREAD

**Issue by rockneverdies55** [nikku/karma-browserify#183]
Any version after v4.4.2 emits "error parsing file unexpected token" for jsx syntax within test scripts.  
However when 4.4.2 is used transformation works correctly...

**Comment by nikku** [comment]
With `5.x` the browserify version used changed to whatever you define in your project (it is now a peer dependency). Maybe that causes the issues?

Please add a test case (example project) that reproduces the issue if we should look into it.

**Comment by nikku** [comment]
Feel free to provide additional information and we are happy to work on this.

**Comment by dwelle** [comment]
Same problem. Local browserify version was `12.0.1`, bumping to `13.0.1` solved the issue. Perhaps the peer dependency shouldn't allow `<13`?
