### ISSUE TITLE
Overly strict peer dependency causes npm to fail

### ISSUE THREAD

**Issue by daprahamian** [nikku/karma-browserify#188]
[Browserify just released 13.0.1](https://github.com/substack/node-browserify/releases/tag/13.0.1). The peer dependency requiring `<=13.0.0` is breaking npm install.

**Comment by bendrucker** [comment]
Fixing now 1ea06cb81c10930c327909a7b36682bed6cc5fa3 ae3d09f7b44ea8d928600a16f466c5335861ad15

**Comment by thehindenburg** [comment]
IMO it would be better to leave these open until the fix has been completed.
