### ISSUE TITLE
autowatch: false with singleRun: false don´t work

### ISSUE THREAD

**Issue by bySabi** [nikku/karma-browserify#201]
I clone `karma-browserify` example and set `singleRun` to false but test never start. It stuck in this line: 

```
28 08 2016 00:00:28.400:DEBUG [karma]: A browser has connected on socket /#Eq842Snvk0BAzXC8AAAA
28 08 2016 00:00:28.403:DEBUG [web-server]: upgrade /socket.io/?EIO=3&transport=websocket&sid=Eq842Snvk0BAzXC8AAAA
28 08 2016 00:00:28.439:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket /#Eq842Snvk0BAzXC8AAAA with id 8306171
28 08 2016 00:00:28.440:DEBUG [launcher]: PhantomJS (id 8306171) captured in 1.667 secs
```

Setting `autowatch` to  true works fine, test get passed.

**Comment by nikku** [comment]
We have got [a test case](https://github.com/nikku/karma-browserify/blob/master/test/spec/integrationSpec.js#L59) that verifies this works. With `v5.1.0` at least.
