### ISSUE TITLE
Move `watchify` to optionalDependencies?

### ISSUE THREAD

**Issue by isiahmeadows** [nikku/karma-browserify#202]
Building off of #193, I think it might be better for it to be listed as an optional dependency. `npm` will still warn about incompatible versions with optional dependencies, but it won't warn about them not being installed (they're *optional*, after all). Like peer dependencies, they aren't automatically installed.

**Comment by isiahmeadows** [comment]
Nope...won't work: npm/npm#3066

**Comment by partounian** [comment]
This is a bit old, but I'm having issues with it as a peerDependency and can't seem to remove that requirement as npm install or yarn will just repull the file and try running that. Any way to get around this issue?

**Comment by isiahmeadows** [comment]
@partounian I'd consult https://github.com/npm/npm/issues/3066 and maybe file an equivalent issue in Yarn's repo, since they are the ones blocking this.

**Comment by partounian** [comment]
So no workaround just to get this to build?

**Comment by isiahmeadows** [comment]
The workaround is just to `npm install --save-dev watchify`.
