### ISSUE TITLE
Not able to require module packages with CommonJS

### ISSUE THREAD

**Issue by JuanCaicedo** [nikku/karma-browserify#204]
I mentioned this problem in https://github.com/jamesshore/quixote/pull/37, but the maintainer thought the problem might be with this plugin.

To recreate, you can 

```bash
$ git clone https://github.com/JuanCaicedo/tdd-css.git
$ cd tdd-css
$ git fetch origin
$ git checkout quixote-published
$ npm install
$ npm test
```

Any help would be appreciated! 😃

**Comment by bendrucker** [comment]
If you point browserify directly at one of your test modules will it bundle?

**Comment by JuanCaicedo** [comment]
Thanks for the quick response! I tried pointing browserify directly on this branch <https://github.com/JuanCaicedo/tdd-css/tree/manual-browserify>

If I do these steps

```bash 
$ npm install
$ browserify test/accent-box.js -o lib-test/accent-box.js -t [ babelify --presets [ es2015 ] ]
```

The build fails with the following error

```
Error: Cannot find module './util/ensure.js' from '/Users/JuanCaicedo/code/speaking/quixote-browserify/node_modules/quixote/dist'
    at /Users/JuanCaicedo/code/speaking/quixote-browserify/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/JuanCaicedo/code/speaking/quixote-browserify/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/JuanCaicedo/code/speaking/quixote-browserify/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/JuanCaicedo/code/speaking/quixote-browserify/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

That makes me think it's a problem with how the `quixote` module is built?

**Comment by bendrucker** [comment]
> That makes me think it's a problem with how the quixote module is built?

Yup, that definitely confirms it! My guess is that it's using `require` internally even if it's a self-contained bundle. Can't do that, it'll cause bundlers like browserify to try to find those modules.

**Comment by JuanCaicedo** [comment]
Perfect @bendrucker thanks!
