### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by sgen** [nikku/karma-browserify#207]
Im getting the following error when trying to import my module for testing: `Error: Cannot find module 'test-karma-browserify'`. I get the same error whether I try to import my module by name or by relative path.

[Here](https://github.com/sgen/test-karma-browserify) is a repro repo.

Any help you can offer is much appreciated!

**Comment by nikku** [comment]
Do not preprocess your sources, preprocess the test cases instead. 

Cf. [example project](https://github.com/nikku/karma-browserify/blob/master/example/karma.conf.js).

**Comment by sgen** [comment]
Swapping the `index.js` for `test.js` in the preprocessor section of the config fixed the original error, but also created a new error in the module file: `Uncaught ReferenceError: module is not defined` [ab3f95](https://github.com/sgen/test-karma-browserify/commit/ab3f954c9734d608becbbb3d911e799cc78bb897).

Preprocessing both the module and test cases fixed the error: (5e8f55)[https://github.com/sgen/test-karma-browserify/commit/5e8f5593c8e3fafa640e4ebc654c0263914427f3].

Is that just a product of the exporting as well as importing?
