### ISSUE TITLE
ERROR [framework.browserify]: Error: Cannot find module

### ISSUE THREAD

**Issue by krnbatta** [nikku/karma-browserify#211]
When i run tests via karma, i get ERROR [framework.browserify]: Error: Cannot find module for all the files in js folder. Here is the structure of my app.
`app/js/**/*.js`, `app/tests/**/*.js`, `app/karma.conf.js`

Following is my karma.conf.js file:
```
module.exports = function(config) {
    config.set({

        basePath: '',
        frameworks: ['browserify', 'jasmine'],
        browsers: ['Chrome'],
        files: [
            'js/**/*.js',
            'tests/**/*.js'
        ],

        exclude: [],

        preprocessors: {
            'js/**/*.js': ['browserify'],
            'tests/**/*.js': ['browserify']
        },

        browserify: {
            debug: true,
            transform: ['babelify']
        },
    });
};

```
In js folder, where i have code, i have used import statements using relative paths. Eg.: 
`import Store from '../../services/store';`
`import template from './template';`

**Comment by nikku** [comment]
Don't include source files as part of the `files` configuration.

**Comment by Mifrill** [comment]
Hello, @krnbatta. Did you solve your problem? I've got the same error with ember config, perhaps your solution would be partly-helpful for me. Thanks
