### ISSUE TITLE
Missing repo nikku/node-browserify breaks older versions (<4.0)

### ISSUE THREAD

**Issue by dylanbr** [nikku/karma-browserify#213]
Specifically for me this is affecting https://github.com/oauthjs/angular-oauth2

**Comment by nikku** [comment]
I'm sorry this affects you. Unfortunately, `nikku/node-browserify` is gone without replacement.

As a workaround I highly recommend anyone still using karma-browserify@4 to switch to karma-browserify@5 which is battle tested, two years old and which does not require a custom fork of the `browserify` library. 

As a work around in your specific case, try to upgrade the `karma-browserify` version to 5 and see if the `oauthjs/angular-oauth2` still runs:

```
npm install --save-dev karma-browserify@latest browserify watchify
```
