### ISSUE TITLE
Unable to browserify file 

### ISSUE THREAD

**Issue by asghar3** [nikku/karma-browserify#215]
I not able to browserify js file that requires one scoped node module from node_modules dir:
The standalone browserify works for the same file.
I am using the latest version for browserify and karma-browserify

I mentioned browserify in karma-config.json

frameworks: ['jasmine', 'XXX', 'browserify'],
browserify: {
            debug: true
        },

```
Chrome 62.0.3202 (Mac OS X 10.13.1) ERROR
  Uncaught TypeError: Cannot read property 'prototype' of undefined
  at /var/folders/f7/pbrckg910w38p4z01llqvv9c0000gp/T/node_modules/graceful-fs/graceful-fs.js:166:0 <- /var/folders/f7/pbrckg910w38p4z01llqvv9c0000gp/T/c67c90f53865c8e01979581b7ded28a0.browserify:5262
13 12 2017 16:40:16.003:DEBUG [reporter.XXX]: START 'onBrowserComplete' function
13 12 2017 16:40:16.003:DEBUG [reporter.XXX]: END 'onBrowserComplete' function

Chrome 62.0.3202 (Mac OS X 10.13.1): Executed 0 of 0 ERROR (0.152 secs / 0 secs)

13 12 2017 16:40:16.015:DEBUG [reporter.XXX]: START 'onRunComplete' functions
13 12 2017 16:40:16.015:ERROR [reporter.XXX]: ERROR : unexpected error detected.
```

Not sure to why it is giving error for graceful-fs.
Need help to resolve this issue.

**Comment by bendrucker** [comment]
karma-browserify does not include `graceful-fs` anywhere in its dependency tree. If you're saying that's unrelated and want us to take a deeper look, please share an example project we can use to easily and quickly reproduce your problem. I'm pretty certain this is not a karma-browserify bug and with the information you've shared I can't offer useful guidance on where to look.
