### ISSUE TITLE
Install issues due to browserify peerDependecy condition

### ISSUE THREAD

**Issue by kunagpal** [nikku/karma-browserify#216]
[browserify 15.0.0](https://github.com/browserify/browserify/blob/master/changelog.markdown#1500) has been released, which is resulting in installation issues with karma-browserify `v5.1.2` due to the `peerDependency` condition of: 
```json
  "peerDependencies": {
    "karma": ">=0.10.0",
    "browserify": ">=10 <15",
    "watchify": ">=3 <4"
  }
```

Node version: v4.8.7
npm version: v2.15.11

**Comment by bendrucker** [comment]
Next time please submit a PR, it'll save time for both you and the project maintainers
