### ISSUE TITLE
karma-browserify

### ISSUE THREAD

**Issue by mingyaaaa** [nikku/karma-browserify#217]
I can not debug my code that use  karma-browserify in vsocde  
![image](https://user-images.githubusercontent.com/11772546/38941550-5d4d4d76-435f-11e8-8376-d6dc9c3337e4.png)
it's seem that the sourcemap is error

**Comment by bendrucker** [comment]
Hey I'm sorry but this isn't an actionable ticket for us. If you can provide evidence that there's something wrong with the sourcemap we can certainly take a look but we can't provide support for editors, especially not on the basis of a screenshot and two sentences.
