### ISSUE TITLE
promisify is not a function

### ISSUE THREAD

**Issue by ManukumarB** [nikku/karma-browserify#224]
![image](https://user-images.githubusercontent.com/69336870/89609847-a3061400-d896-11ea-8149-a8c7ac081da3.png)
![image](https://user-images.githubusercontent.com/69336870/89609911-cfba2b80-d896-11ea-981e-517816ae29a6.png)

**Comment by ManukumarB** [comment]
Node version v12.18.3

**Comment by bendrucker** [comment]
Hi, please share text and not screenshots. A full stack trace would be helpful. There's no clear indication this is a bug, but if further info indicates I'm happy to reopen.
