### ISSUE TITLE
Cannot use import statement outside a module only on karma-browserify

### ISSUE THREAD

**Issue by shirblc** [nikku/karma-browserify#226]
Hi,

I have an issue with karma-browserify and bundling up test files. Bundling seems to go perfectly fine when bundling tests separately, but when I try doing it through karma-browserify Karma errors with `Uncaught SyntaxError: Cannot use import statement outside a module`. On the other hand, when I bundle the tests and then run Karma with that tests file, Karma runs perfectly fine and detects all tests. 

I've tried searching online, but I can't seem to be able to figure out what the difference is between the Gulp task [(here)](https://github.com/shirblc/angular-gulp/blob/b67189f13c8f4c0a310f6de4983f18b24b1e3def/gulpfile.js#L191) and the karma-browserify config ([here](https://github.com/shirblc/angular-gulp/blob/replace-webpack/karma.conf.js)).

Could anyone help?

[Sample repo](https://github.com/shirblc/angular-gulp/tree/replace-webpack), ready with the relevant Gulp tasks and Karma config. Just needs to install dependencies and run `gulp test`.

Thank you!

**Comment by shirblc** [comment]
Never mind, seems to be my error. On a side note, it might be worth replacing 'prebundle' with 'bundle' in the README as it seems to be the updated way to apply transforms and plugins.

**Comment by nikku** [comment]
> Never mind, seems to be my error. 

Thanks for the heads up.

> On a side note, it might be worth replacing 'prebundle' with 'bundle' in the README as it seems to be the updated way to apply transforms and plugins.

Do you have a reference for me where I can look this one up?

**Comment by shirblc** [comment]
I can't seem to find a direct reference to it, but I haven't found any references to prebundle after 2015, and Browserify's samples (And a lot of the plugins / transforms) use bundle.plugin/transform instead of the prebundle hook, like this:
```
configure: function(bundle) {
        bundle.plugin('tsify', { target: 'es6' }).transform('browserify-istanbul');
      }
```
(That's the configuration that worked, by the way).
So 'prebundle' doesn't seem needed anymore (nor did it seem to be working for me, but as said, that seemed to be my error).
