### ISSUE TITLE
Support for Browserify v17

### ISSUE THREAD

**Issue by GMartigny** [nikku/karma-browserify#227]
Hello,

As per `karma-browserify`'s `peerDependencies`, [Browserify@17](https://github.com/browserify/browserify/releases/tag/v17.0.0) is not supported.

Would it be possible to upgrade the `peerDependencies` to allow the use of Browserify@17 ?

Thanks

**Comment by nikku** [comment]
Happy to take a PR that adds `browserify@17` support.

**Comment by nikku** [comment]
Thanks @bendrucker :tada:.
