### ISSUE TITLE
Breaking change coming for karma-browserify/lib/preprocessor.js 

### ISSUE THREAD

**Issue by johnjbarton** [nikku/karma-browserify#228]
The monkey patch code in this file will break in the next release of karma.

AFAICT the code is mutating the config to attach browserify-bundle to *.browserify.js?  Why?

**Comment by johnjbarton** [comment]
I found a way to make this work for now.

**Comment by nikku** [comment]
Which way did you find? Could help others using the tool, too.

More context would also help us to prevent the karma update from breaking our preprocessor, too.

**Comment by johnjbarton** [comment]
Google's internal build system (open sourced as bazel) supports binding a karma.conf.js with each karma plugin. This has worked well for us. If karma supported this at the nodejs level then your monkey patch would not be needed.  It could be as simple as `require('<plugin>/karma.conf.js')`.  WDYT?

**Comment by nikku** [comment]
I'm lacking the details on what you would like to achieve and why. 

If karma-browserify is the cause of any trouble, create a new issue with concrete steps to reproduce.
