### ISSUE TITLE
Support watchify <= 4

### ISSUE THREAD

**Issue by jlafuenteribera** [nikku/karma-browserify#229]
karma-browserify@8.0.0 requires a peer of watchify@>=3 <4 but none is installed. You must install peer dependencies yourself.

**Comment by nikku** [comment]
What exactly is your issue?

**Comment by dmihalcik-virtru** [comment]
Currently, watchify 3.x triggers a transitive dep on a version of glob-parent with this vulnerability: https://www.npmjs.com/advisories/1751
