### ISSUE TITLE
Passing paths option 

### ISSUE THREAD

**Issue by maxcal** [nikku/karma-browserify#32]
Is it possible to pass the paths option to browserify? 

I´m trying to get a previous setup with `gulp-mocha` running where I have my sources in `js/src/myapp`.
And I require the files under test without the relative path: `require('myapp/foo')`.

I have tried adding: 

``` JAVASCRIPT
// karma.conf.js
module.exports = function(config) {
  config.set({

   // ...

   browserify: {
        debug: true,
        paths: ['./src/js']
    }, 
   });
};
```

And also adding the option to `package.json`. But browserify does´nt pick up the paths. Any ideas?

**Comment by ebenoist** [comment]
@bendrucker looks like `opts.paths` is now officially documented. Would you be interested in a pull request exposing that option? The `opts.paths` option is incredibly useful for applications that have a deeply nested directory structure (ie. a Rails project).

**Comment by hamishtaplin** [comment]
Will this ever be fixed?

**Comment by nikku** [comment]
It works out of the box ([example](https://github.com/bpmn-io/bpmn-js/blob/master/test/config/karma.unit.js#L42)).
