### ISSUE TITLE
Sometimes tests don't run at all with autoWatch=true

### ISSUE THREAD

**Issue by telegraphinho** [nikku/karma-browserify#75]
Hi. It's a strange issue i'm having. First time i run `karma karma.conf.js` it runs well, but when i change my test files it sometimes runs the tests and sometimes doesn't(although it seems that it runs them twice!). I tried setting `bundleDelay` as high as `3000`, but it doesn't help. I'll explain what i mean. First, here's my config file:

```javascript
'use strict';

module.exports = function (karma) {

  karma.set({

    basePath: '../',

    colors: true,

    frameworks: [
      'browserify',
      'jasmine',
      'jasmine-matchers'
    ],

    preprocessors: {
      './test/unit/**/*.coffee': ['browserify']
    },

    browsers: ['PhantomJS'],

    reporters: ['mocha'],

    browserify: {
      transform: ['coffeeify', 'brfs', 'browserify-shim'],
      extensions: ['.coffee'],
    },

    autoWatch: true,

    logLevel: 'LOG_DEBUG',

    files: [
      './js/vendor/jquery/jquery.js',
      './js/vendor/lodash/lodash.compat.js',
      './js/vendor/**/*.js',
      './test/unit/**/*.coffee'
    ]

  });

};

```

Here's my spec file:

```coffeescript
'use strict'

describe 'vendor libraries', ->

  describe 'jQuery', ->
    it 'should be defined on window', ->
      expect(window.jQuery)
        .toBeObject()
```

So the first time i run `karma karma.conf.js`, it runs this test and it passes.

Then i edit this file. Lets say i'll do this:

```coffeescript
'use strict'

describe 'vendor libraries', ->

  describe 'jQuery', ->
    it 'should be defined on window, I HOPE SO', ->
      expect(window.jQuery)
        .toBeObject()
```

i added "I HOPE SO".

So i changed this file, saved it and it runs the test twice. Here's the output:

```
INFO [watcher]: Changed file "/Users/le0/Projects/GulpTest/src/assets/scripts/test/unit/vendorSpec.coffee".
DEBUG [framework.browserify]: updating test/unit/vendorSpec.coffee in bundle
DEBUG [framework.browserify]: resetting bundle
DEBUG [framework.browserify]: bundling
INFO [framework.browserify]: 805 bytes written (0.00 seconds)
INFO [framework.browserify]: bundle updated
DEBUG [karma]: List of files has changed, trying to execute
DEBUG [karma]: All browsers are ready, executing
INFO [watcher]: Changed file "/var/folders/n8/wl3658qx0ll4bp3vdhl24j0m0000gn/T/70ba12dbd320662a60e66eef11f82f3f7ba65c8e.browserify".
DEBUG [web-server]: serving (cached): /Users/le0/Projects/GulpTest/node_modules/karma/static/context.html
  vendor libraries
    jQuery
      ✔ should be defined on window

Finished in 0.001 secs / 0.002 secs

SUMMARY:
✔ 1 tests completed
DEBUG [framework.browserify]: files changed
DEBUG [framework.browserify]: resetting bundle
DEBUG [framework.browserify]: removing missing file ../../../test/unit/vendorSpec.coffee
DEBUG [framework.browserify]: bundling
INFO [framework.browserify]: 454 bytes written (0.00 seconds)
INFO [framework.browserify]: bundle updated
INFO [watcher]: Changed file "/var/folders/n8/wl3658qx0ll4bp3vdhl24j0m0000gn/T/70ba12dbd320662a60e66eef11f82f3f7ba65c8e.browserify".
DEBUG [karma]: List of files has changed, trying to execute
DEBUG [karma]: All browsers are ready, executing
DEBUG [web-server]: serving (cached): /Users/le0/Projects/GulpTest/node_modules/karma/static/context.html
PhantomJS 1.9.8 (Mac OS X) ERROR
  ReferenceError: Can't find variable: require
  at /Users/le0/Projects/GulpTest/src/assets/scripts/test/unit/vendorSpec.coffee:1

Finished in 0.276 secs / 0 secs

SUMMARY:
✔ 0 tests completed
```

As you can see, it runs it two times now. First time it looks like it runs, but then it somehow thinks the file changed again and it tries to run again. Now it gives the error
```
'PhantomJS 1.9.8 (Mac OS X) ERROR
  ReferenceError: Can't find variable: require
  at /Users/le0/Projects/GulpTest/src/assets/scripts/test/unit/vendorSpec.coffee:1
```

But notice this: on the first run, the test doesn't say 'I HOPE SO'. It says what was previously there.

So the test didn't run at all!

If i save this file again it might run normally, but it might do the same thing again. It's completely random. It 100% works only the first time i launch it.

Also sometimes it gives me another error, when i first launch `karma karma.conf.js`

```
PhantomJS 1.9.8 (Mac OS X) ERROR
  TEST RUN WAS CANCELLED because this file contains some errors:
    /var/folders/n8/wl3658qx0ll4bp3vdhl24j0m0000gn/T/70ba12dbd320662a60e66eef11f82f3f7ba65c8e.browserify
```

I do `karma karma.conf.js` again and it works fine... Go figure.

Versions of all npm packages are latest as of today.

If you need anything else, i can create an example repo. I'm just trying this stuff out so i might've made a mistake and maybe it's my own fault and not an issue with your cool package.

One thing i can say is that it's not `jasmine-matchers` plugin's fault, because it worked like that before i added it.

**Comment by Nikku** [comment]
Could you create an example repository that reproduces the issue?

**Comment by telegraphinho** [comment]
There you go: https://github.com/telegraphinho/karma-browserify-test

There's a bug with browserify installation now(it was introduced a couple of hours ago). The workaround is in the first lines of readme file.

**Comment by webfella** [comment]
I'm having the same problem as @telegraphinho, I haven't been able to find a solution... but noticed it's guaranteed to happen with autoWatch enabled and the module being tested (not the test) is edited.

**Comment by telegraphinho** [comment]
@webfella, for me it happens with the test file itself too. Most often when i add the a new test(`it` block). Sometimes when i remove or comment some test or just change something else. But it's not as often as with adding a new one.

**Comment by bendrucker** [comment]
> Most often when i add the a new test(it block). Sometimes when i remove or comment some test or just change something else. But it's not as often as with adding a new one.

Pretty certain this is not the case. There's no way the effect could be so dependent on your code.

@webfella Are you on OS X as well?

**Comment by telegraphinho** [comment]
@bendrucker, yeah. Probably just a coincidence. Anyways, that's what i noticed.

The problem doesn't happen when autoWatch=false or singleRun=true. That's for sure. Tested multiple times.

**Comment by webfella** [comment]
@bendrucker Yeah mate, OS X here too. Just at a quick glance, it seems as if the time when it fails it's not bundling correctly as I logged out the buffer and it was only around 450b.

**Comment by Nikku** [comment]
I can verify this is not an issue on Arch Linux.

It may be a caching issue related to the coffee-script transform though (don't know if it actually caches things).

**Comment by webfella** [comment]
@Nikku I'm getting the issue without any transforms in the project. I can put up a version on github with the use case I'm running into in a few hours if that helps.

**Comment by Nikku** [comment]
That would be good.

**Comment by bendrucker** [comment]
I'll take the lead on digging in on this since it's OS X-specific. I also just got in touch with Travis about getting included on the multi-OS beta. Might be hard to impossible to get a reliable failing test against this but I'd like to try anyway.

**Comment by bendrucker** [comment]
@telegraphinho what you referenced in https://github.com/nikku/karma-browserify/issues/75#issuecomment-68533083 is unrelated. I just closed thlorenz/proxyquireify#21 last night. That was actually a proxyquireify bug. 

Will work on @webfella's repro now.

**Comment by bendrucker** [comment]
Hmm. So what's actually going on here is that no files are getting included in the bundle when it's rebuilt after a change to a source file. Investigating...

**Comment by webfella** [comment]
@bendrucker Yeah I couldn't track it down apart from removing the part that deletes missing files, which obviously isn't ideal.

**Comment by webfella** [comment]
Thanks a lot guys, I just verified the patch works for my use case. Looking forward to seein it on npm.

Cheers

**Comment by nikku** [comment]
Just released the fixes with karma-browserify@3.0.0.

**Comment by webfella** [comment]
Thanks for the heads up @nikku

**Comment by webfella** [comment]
I have a question regarding autoWatch, that I thought I'd ask here instead of starting a new issue.

Is there a way through the library to only run the tests affected by the change, ie a change to the "foo" module only triggers the "foo" tests instead of the entire suite? I havn't found a way to do it yet with browserify.

**Comment by nikku** [comment]
This is something that would be a feature of karma-browserify rather than browserify. It is not implemented though and not the way karma works, too.

You can yield a similar behavior yourself though: If you are using mocha, specify `it.only(...)` to run a focused test. Use `iit(...)` in jasmine.

**Comment by webfella** [comment]
Thanks for clearing that up mate, much appreciated.

**Comment by dallasclark** [comment]
I'm having this issue now with the latest release. Oddly, I'm the only developer in a team of 6 experiencing this issue.

When I run the following command: $ grunt unit (Task: clean:reports install_custom_coverage karma:unit), I receive the following result:
```...
DEBUG [web-server]: serving: C:\Dev\life-web_components\node_modules\karma\static/context.html
PhantomJS 1.9.8 (Windows 7) ERROR
  TEST RUN WAS CANCELLED because this file contains some errors:
    C:/cygwin/tmp/2cfb2e9479b44a59f6d3c57d366bd5b4.browserify


IE 8.0.0 (Windows 7) ERROR
  TEST RUN WAS CANCELLED because this file contains some errors:
    C:/cygwin/tmp/2cfb2e9479b44a59f6d3c57d366bd5b4.browserify

Chrome 41.0.2272 (Windows 7) ERROR
  TEST RUN WAS CANCELLED because this file contains some errors:
    C:/cygwin/tmp/2cfb2e9479b44a59f6d3c57d366bd5b4.browserify



DEBUG [karma]: Run complete, exiting.
DEBUG [launcher]: Disconnecting all browsers
DEBUG [framework.browserify]: cleaning up
DEBUG [launcher]: Process PhantomJS exited with code 0
DEBUG [temp-dir]: Cleaning temp dir C:\cygwin\tmp\karma-34162292
DEBUG [launcher]: Process Chrome exited with code 0
DEBUG [temp-dir]: Cleaning temp dir C:\cygwin\tmp\karma-61774528
DEBUG [reporter.junit]: JUnit results written to "C:/Dev/life-web_components/reports/unit_tests.xml".

DEBUG [launcher]: Killed extra IE process 6528
DEBUG [launcher]: Process IE exited with code 0
DEBUG [temp-dir]: Cleaning temp dir C:\cygwin\tmp\karma-94332604
Warning: Task "karma:unit" failed. Use --force to continue.

Aborted due to warnings.```

I've tried a range of suggestions, restarting CMDER, restarting machine, deleting node_modules, reinstalling global node modules, set autoWatch to false and various other attempts with no luck.

As I'm the only developer in the team experiencing the issue, it appears to be environment related.

**Comment by dallasclark** [comment]
Please ignore previous post, it turned out to be a component in our repo that required `npm install` within the directory to install it's dependencies.
