### ISSUE TITLE
Improve the example to use transforms

### ISSUE THREAD

**Issue by oveddan** [nikku/karma-browserify#76]
[The example](https://github.com/Nikku/karma-browserify/tree/master/example) right now doesn't show a setup that uses transforms (coffeeify/reactify) - it would be great if either:
a) The existing example was enhanced to show a configuration with transforms.
b) A new example was created showing a configuration with transforms (coffeeify, reactify, or both).

I, for one, am facing immense difficulty getting this to work with coffeeify, when coffeescript files are required from outside of the tests folder.  An example here would be really helpful.

**Comment by Nikku** [comment]
Feel free to create a pull request that updates the example and adds coffescript support.

We can discuss and finalize it on the PR.

**Comment by bendrucker** [comment]
We'll happily take PRs that add new examples for common variants of particular configurations.

**Comment by oveddan** [comment]
Sounds good, when time permits will work on this.
