### ISSUE TITLE
Generating full bundle for preprocessed file

### ISSUE THREAD

**Issue by Kagami** [Nikku/karma-browserify#79]
Hi. Thank you for such a great plugin.

I have quite strange use case and I don't know is it possible to accomplish using `karma-browserify`. I need to testing Web Workers using karma and because workers have entire separate context the common way of loading test cases doesn't work: the workers fail with error message: `Error: Uncaught ReferenceError: require is not defined`.

To illustrate that. Say I added `worker.js` to the list of `files` and to the `preprocessors` object. Now if I fetch that file while karma is running I will get something like:

```
$ curl http://localhost:9876/base/worker.js
require("/home/user/test/worker.js");
```

When I run `new Worker("/base/worker.js")` inside the test, browser trying to evaluate this code inside the new web worker and fails because `require` is undefined.

So, is it possible to generate full bundle for some file? I was trying to play with `browserify.configure` option but with no luck.

Also, I'm aware that I can always run `browserify worker.js > bundle.js` to produce the full bundle before running the karma but I'd like to do it via karma (because of the watching, logging stuff, etc.).
Thanks.

**Comment by bendrucker** [comment]
Thought about this a little and I'm not sure there's a good way to support this

**Comment by Nikku** [comment]
[webworkify](https://www.npmjs.com/package/webworkify) exists that allows you to use browserified scripts in your webworkers. It should help you to access `require` calls in webworkers.

**Comment by Kagami** [comment]
Thanks! Looks good!
(The only thing that worry me a bit is performance: my worker code weights 79K, not sure is it good to pass it as string instead of let worker download it from URL and cache, etc.)
