### ISSUE TITLE
Broken without code changes 

### ISSUE THREAD

**Issue by Dakuan** [nikku/karma-browserify#81]
I'm getting the dreaded 
```
PhantomJS 1.9.8 (Mac OS X) ERROR
  TypeError: 'undefined' is not a function (evaluating 'require("/Users/Dom/git/nabu/tests/specs/iso/actions/projects-actions-spec.js")')
  at /Users/Dom/git/nabu/tests/specs/iso/actions/projects-actions-spec.js:1
```
but this has suddenly started happening by itself - no code has changed, and reverting to older versions doesn't help.

I did have this happen once before - but was able to fix my cleaning my npm cache. This isn't working now, and the tests fail every time.

**Comment by bendrucker** [comment]
Please create a project that reproduces this. We're happy to help on general issues but this does not sound like it's a karma-browserify issue.
