### ISSUE TITLE
Dependency on Git

### ISSUE THREAD

**Issue by davidtheclark** [nikku/karma-browserify#82]
Looks like the fork of Browserify that this package depends on depends on Git being installed on the system. That's a significant dependency ... any chance it can be done away with? Why is it necessary?

**Comment by nikku** [comment]
How is it depending on git? Via the GitHub project reference?

**Comment by nikku** [comment]
And by the way, I hope this is only a temporary issue until browserify merges a number of crucial bug fixes, see [here](https://github.com/nikku/node-browserify/compare/karma-browserify).

**Comment by bendrucker** [comment]
He means the node-browserify dep on GitHub versus the usual npm. And yeah, it can't be done away with until https://github.com/substack/node-browserify/pull/1037 and https://github.com/substack/node-browserify/pull/1034 get merged.

**Comment by davidtheclark** [comment]
Yes. Thanks for the explanation! Hopefully it gets merged soon.
