### ISSUE TITLE
'Cannot find module' issue persists on Windows 8.1

### ISSUE THREAD

**Issue by divmgl** [nikku/karma-browserify#89]
I'm still receiving this issue on Windows 8.1.

https://github.com/divmgl/karma-browserify-windows81-issue

Clone this project and run Grunt. This will be the output.

```
INFO [framework.browserify]: registering rebuild (autoWatch=true)
WARN [karma]: Port 9876 in use
INFO [karma]: Karma v0.12.31 server started at http://localhost:9877/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Windows 8)]: Connected on socket wYLOi3iPPyXZKnNppEaD wit
h id 64695440
INFO [framework.browserify]: 935699 bytes written (0.77 seconds)
INFO [framework.browserify]: bundle built
PhantomJS 1.9.8 (Windows 8) ERROR
  Error: Cannot find module 'c:\Users\Dexter\Source\Repos\karma-browserify-proof
\test\framework.js'
  at c:/Users/Dexter/AppData/Local/Temp/3a2bf222464417fa85b4e55034eee16faf2aed56
.browserify:1:0 <- node_modules\karma-browserify\node_modules\browserify\node_mo
dules\browser-pack\_prelude.js:1:0

Finished in 0.97 secs / 0 secs

SUMMARY:
√ 0 tests completed
```

I have confirmed that this does not happen in Windows 7.

**Comment by bendrucker** [comment]
Any insight you can offer as a Windows user is hugely helpful. I don't have access to a Win box but will work on #90 to increase the chances of catching these issues in the future. I usually handle Mac stuff related to fsevents and Nico uses Linux which tends to cause the least trouble. Wouldn't even know where to start looking with Windows, especially with an issue this weird.

**Comment by nikku** [comment]
Will check whether this issue can be reproduced on Win 7 soon. If so, I see good chances we can track down the problem. 

As Ben said, we appreciate any help for digging into this on Windows 8.

**Comment by divmgl** [comment]
I have made a fresh install of Windows 8.1 and installed Node v0.11.14 and I can confirm that it is working as intended. I apologize for this; may have been an old cached version of karma-browserify or an older version of Node or Browserify.
