### ISSUE TITLE
Configure AppVeyor in CI

### ISSUE THREAD

**Issue by bendrucker** [nikku/karma-browserify#90]
Windows is bad and it should feel bad. I'm going to take care of setting up [Appveyor](http://www.appveyor.com/) in hopes of catching Windows bugs more quickly.

**Comment by StoneCypher** [comment]
Hi, I'm a Windows developer.  I use your work and I'm thankful for your help.

Please remember that we're the vast majority of developers.

**Comment by bendrucker** [comment]
Thank you!

**Comment by bendrucker** [comment]
When you edit things it's still cached in the feed ;)

> Please remember that we're the vast majority of developers.

I have no idea how the numbers stack up to be honest. I get that hearing that your platform sucks gets old. The best way to go about it is to respect the time and effort of maintainers as you've done here. We don't want to spend a bunch of extra time trying to track down bugs on a foreign platform and the more the Windows + Node community can do to help itself the more things will smooth out.
