### ISSUE TITLE
Viewing the built file or config to save the built file at a known location

### ISSUE THREAD

**Issue by gching** [nikku/karma-browserify#94]
Is there a way to view the built file after a test run? Of course, I can access it through the assets but because every time it changes the file name, I would rather have a specific location where I know where the built file is for me to check errors at specific locations. Thanks!

**Comment by nikku** [comment]
Specify autoWatch + bump up the LOG_LEVEL in order to get the path of the bundle file.

This way you may have a look into it, i.e. using Chrome or on the file system.
