### ISSUE TITLE
Different require style produces strange error in the karma-browserify example. 

### ISSUE THREAD

**Issue by danielyogel** [nikku/karma-browserify#95]
I've cloned the example from this repo, npm installed the dependencies, then used "karma start" and everything worked as expected.

Then **only** changed the require part of test.bSpec.js from
``` var fs = require('fs');
var b = require('../lib/b'); ```
to 
``` var fs = require('fs'),
    b = require('../lib/b'); ```

And the karma start produced an error.
I'm not an expert with Browserify, but that feels like a bug.

Thanks a lot ! (the error text is down here)

**update**
Seems like the problem is something about the brfs transform, I have removed the code that uses it, and the transform itself from karma configs, an the error disappeared. 


````
INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket PCfNr4sarFlw8U78zy0L with id 97878544
DEBUG [launcher]: PhantomJS (id 97878544) captured in 0.425 secs
DEBUG [framework.browserify]: bundling
ERROR [framework.browserify]: bundle error
ERROR [framework.browserify]: Error: Parsing file /home/daniel/Code/EXAMPLES/karma-browserify/example/test/bSpec.js: Unexpected token (6:8)
DEBUG [watcher]: Resolved files:
        /home/daniel/Code/EXAMPLES/karma-browserify/example/node_modules/karma-jasmine/lib/jasmine.js
        /home/daniel/Code/EXAMPLES/karma-browserify/example/node_modules/karma-jasmine/lib/adapter.js
        /home/daniel/Code/EXAMPLES/karma-browserify/example/vendor/external.js
        /tmp/b996aa9b9ac220ab0c9115f02911818850175caf.browserify
        /home/daniel/Code/EXAMPLES/karma-browserify/example/test/bSpec.js
        /home/daniel/Code/EXAMPLES/karma-browserify/example/test/externalSpec.js
DEBUG [web-server]: serving: /home/daniel/Code/EXAMPLES/karma-browserify/example/node_modules/karma/static/context.html
PhantomJS 1.9.8 (Linux) ERROR
  TEST RUN WAS CANCELLED because this file contains some errors:
    /tmp/b996aa9b9ac220ab0c9115f02911818850175caf.browserify
PhantomJS 1.9.8 (Linux): Executed 0 of 0 ERROR (0.536 secs / 0 secs)
DEBUG [karma]: Run complete, exiting.
DEBUG [launcher]: Disconnecting all browsers
DEBUG [framework.browserify]: cleaning up
DEBUG [launcher]: Process PhantomJS exited with code 0
DEBUG [temp-dir]: Cleaning temp dir /tmp/karma-97878544

````

**Comment by bendrucker** [comment]
This is not a karma-browserify bug. If you want to create a full reproducible example that we can clone I can take a few mins to help troubleshoot.

**Comment by danielyogel** [comment]
Was just about to delete my issue here, it's a known bug in brfs - https://github.com/substack/brfs/issues/28

It may be smart to remove brfs from the example, just because this bug wasted one hour of my time, and that can happen to other people too. But that's just my personal opinion...

Thanks for karma-browserify !
