### ISSUE TITLE
No provider

### ISSUE THREAD

**Issue by peter-mouland** [nikku/karma-browserify#96]
```
Error: No provider for "framework:browserify"! (Resolving: framework:browserify)
```

anyone else getting this issue?
    "karma-browserify": "^3.0.1"

**Comment by bendrucker** [comment]
We have integration tests so it's safe to say that this is an issue with your setup. Make sure you have karma-browserify installed properly and if you're using the `config.plugins` setting in your karma config file make sure it's there. If you don't use that config option karma will load all packages matching `/^karma\-/`. 

If you've checked all those things, please get a repo online reproducing your setup so we can help out.

**Comment by noren** [comment]
Same issue here, fixed by adding:

    plugins: [
      'karma-browserify'
    ],

to kurma config

**Comment by peter-mouland** [comment]
fyi. i still get this randomly on circle ci. locally the plugins array isn't needed in my config, but remotely it is :s

**Comment by bendrucker** [comment]
Hmm. I'm inclined to think that's a Karma bug.

**Comment by maranomynet** [comment]
I'm seeing the same (karma 0.12.36 — karma-browserify 4.2.1)
Fixed by adding 'karma-browserify' item to the plugins array.

**Comment by inf3rno** [comment]
Added karma-browserify to the plugins, it still cannot find it in the node_modules, but it is there along with browserify.... :S

**Comment by grassick** [comment]
Same here with node 4.2.1 and browserify 12.0.1 and karma-browserify 4.4.0. Tested browserify 11.2.0, no difference. 

plugins trick did not work:
```
03 11 2015 16:07:42.127:WARN [plugin]: Cannot find plugin "karma-browserify".
  Did you forget to install it ?
  npm install karma-browserify --save-dev
```

I just updated npm 3.3.10 recently which uses the new flat structure. Could that be it? I'm dead in the water with this bug, unfortunately.

**Comment by inf3rno** [comment]
@grassick On windows my nodejs loaded the global modules first and not the locals, that cause the problem. Now I call it with `node ./node_modules/karma/bin/karma start`. Try out maybe it helps to you too. I am not sure whether I opened an issue about this in the node repo.

**Comment by grassick** [comment]
@inf3rno  Alas, that gives the same problem as before.

**Comment by inf3rno** [comment]
@grassick I opened an issue here: https://github.com/karma-runner/karma/issues/1649
I am not sure whether this is normal behavior on linux, I don't have the time to test it. If you find any difference between op. systems, then please report it. I am not sure whether it is possible to use karma from console when it is only locally installed.
