### ISSUE TITLE
Question - The use of brfs

### ISSUE THREAD

**Issue by Schlogen** [nikku/karma-browserify#98]
In your examples you have the "brfs" transformation, however nowhere is it described whether that is necessary. Is it necessary and if so, why?

Generally the examples should be as lean as possible and not include things that aren't essential in order to avoid confusion.

Thanks for this great module!

**Comment by bendrucker** [comment]
https://github.com/substack/brfs

It's certainly not necessary. It just so happens to be a transform that does something universally useful, versus setup-dependent things like coffeeify that are totally irrelevant if you don't use a particular dev tool.
