### ISSUE TITLE
ReferenceError: Can't find variable: require + empty browserify bundle

### ISSUE THREAD

**Issue by Lucas-C** [nikku/karma-browserify#99]
Hi,

I'm trying to set-up `karma` to run my `tape` tests, hence using `karma-tap` and `karma-browserify`.

On running `karma start`, I get the following error:

    ReferenceError: Can't find variable: require

I'm aware of similar issue #57, but in my case the error is systematic, and the temporary browserify bundle file generated is empty (_/tmp/user/1000/cb88f1cd9cc439321328de693cfef723479b99f4.browserify_).

Would you have any idea on what can cause this issue ?

You can find the full console error log here: https://chezsoi.org/ecovoit/karma_start.log,
and the `npm` / `karma` config on the github project: https://github.com/Lucas-C/ecovoit

**Note:** I also tried to open the karma page with Firefox instead of PhantomJS: same error.

**Comment by nikku** [comment]
You have to add all you test files in the

```
  files: [ ... ]
```

config entry.

Your log should tell you files are recognized and added to the bundle with `LOG_LEVEL=DEBUG`.

**Comment by nikku** [comment]
See the [plug-in usage section](https://github.com/nikku/karma-browserify#usage)

**Comment by Lucas-C** [comment]
I already use `logLevel: 'LOG_DEBUG'` and define the tests `files` to use:
https://github.com/Lucas-C/ecovoit/blob/master/karma.conf.js

**Comment by nikku** [comment]
Nope, you have [commented out the test files](https://github.com/Lucas-C/ecovoit/blob/master/karma.conf.js#L7):

```
  files: [
    'tests/jsonp_utils_test.js',
    //'tests/**/*.js',
  ],
```

**Comment by Lucas-C** [comment]
Nope, I only selected **one** test file to restrict the moving parts and reduce the issue to a simpler scenario.
Should I add anything else than names of test files in that array ?

**Comment by nikku** [comment]
Fair enough. We have to dig deeper into this issue then :smile:.

I cannot see anything wrong with your test configuration. As said, the logs should indicate files files are getting added to the bundle.

I do not know about anyone using tab together with karma-browserify, too. Maybe they are just incompatible.

**Comment by Lucas-C** [comment]
The [`karma-tap`](https://github.com/mapbox/karma-tap) project looks well alive, it has been last updated on January. There is a dedicated [example project](https://github.com/mapbox/karma-tap-example) showing how to use it.
I tried removing the `tap` framework from the config and invoking `karma start` gain: same error.

**Comment by nikku** [comment]
If you want to dig deeper into the issue, build a dedicated example project that uses karma-tap + karma-browserify (just a single test case). I'll do it otherwise as soon as I got time.

**Comment by bendrucker** [comment]
Just looked at your project. This is an easy one. You're adding a file that has `require`s in it: 

https://github.com/Lucas-C/ecovoit/blob/224d55cb6affc4510c6a257d72517bd05f3e92dd/karma.conf.js#L6

But you never preprocess that file because it doesn't match the `test/...` glob.

**Comment by Lucas-C** [comment]
I don't use any glob. Not for the **files** entry.

I gave up on using karma for the moment, but I don't get your answer:
are you suggesting that **tests/jsonp_utils_test.js** is not preprocessed ?

**Comment by bendrucker** [comment]
> are you suggesting that tests/jsonp_utils_test.js is not preprocessed

Yes! Look at what I linked to. This glob is how Karma passes files to karma-browserify: 

https://github.com/Lucas-C/ecovoit/blob/224d55cb6affc4510c6a257d72517bd05f3e92dd/karma.conf.js#L14

And in your `files` you're adding a helper that doesn't match that glob:

https://github.com/Lucas-C/ecovoit/blob/224d55cb6affc4510c6a257d72517bd05f3e92dd/karma.conf.js#L6

And in that file that's not preprocessed you have a bunch of requires: 

https://github.com/Lucas-C/ecovoit/blob/224d55cb6affc4510c6a257d72517bd05f3e92dd/tests/jsonp_utils_test.js#L3-L5

**Comment by bendrucker** [comment]
And the bundle is empty because you're not putting any files in it. Nothing gets preprocessed therefore nothing goes in the bundle.

**Comment by Lucas-C** [comment]
Ok, sorry, I see my mistake now.
Silly me, really. Thanks for your time !

**Comment by bendrucker** [comment]
You got it! 90% of the time stuff like this is exactly this kind of mistake. We've been trying to offer more feedback in the console for config mistakes (e.g. 5a52cf87d30dd3693af8dccd6551c199d9ac100d) but unfortunately this particular one isn't something we can detect.
